config/routes.rb
Rails.application.routes.draw do
  resources :servers do
    scope module: :servers do
      resources :invite_links, only: [:show, :create]
      resources :channels do
        scope module: :channels do
          resources :messages, only: [:create]
        end
      end
    end
  end

  get "/invite/:uniq_id", to: "invitations#show"
  resources :invitations, only: [:create]
  
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboard#show"
end

app/models/server.rb
class Server < ApplicationRecord
  belongs_to :owner, class_name: "User"
  has_many :channels, class_name: "Server::Channel", foreign_key: "server_id"
  has_many :invite_links, class_name: "Server::InviteLink"
  has_many :memberships, class_name: "Server::Membership"
  has_one_attached :image
end

app/models/server/channel.rb
class Server::Channel < ApplicationRecord
  belongs_to :server
  has_many :messages, class_name: "Channel::Message", foreign_key: "server_channel_id"
end

app/models/server/invite_link.rb
class Server::InviteLink < ApplicationRecord
  belongs_to :server

  before_validation :set_uniq_id, if: -> { !uniq_id.present? }

  delegate :name, to: :server, prefix: true

private

  def set_uniq_id
    self.uniq_id = SecureRandom.uuid
    save!
  end
end

app/models/server/membership.rb
class Server::Membership < ApplicationRecord
  belongs_to :user
  belongs_to :server
end

app/controllers/servers/base_controller.rb
module Servers
  class BaseController < ApplicationController
  
  protected
    def authorize_owner!
      redirect_to root_path unless @server.owner == current_user
    end
  end
end

app/controllers/servers/channels/messages_controller.rb
module Servers
  module Channels
    class MessagesController < ApplicationController
      def create
        @server  = Server.find(params[:server_id])
        @channel = @server.channels.find(params[:channel_id])
        @message = @channel.messages.new(message_params)
        @message.user = current_user
        @message.save
        redirect_to server_channel_path(@server, @channel)
      end
    private
      def message_params
        params.expect(channel_message: [ :body ])
      end
    end
  end
end

app/controllers/servers/channels_controller.rb
module Servers
  class ChannelsController < BaseController
    before_action :set_server
    before_action :authorize_owner!, except: %i[ show ]
    before_action :set_server_channel, only: %i[ show edit update destroy ]

    # GET /server/channels or /server/channels.json
    def index
      @server_channels = Server::Channel.all
    end

    # GET /server/channels/1 or /server/channels/1.json
    def show
    end

    # GET /server/channels/new
    def new
      @server_channel = Server::Channel.new
    end

    # GET /server/channels/1/edit
    def edit
    end

    # POST /server/channels or /server/channels.json
    def create
      @server_channel = @server.channels.new(server_channel_params)

      if @server_channel.save
        redirect_to @server, notice: "Channel was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /server/channels/1 or /server/channels/1.json
    def update
      respond_to do |format|
        if @server_channel.update(server_channel_params)
          format.html { redirect_to @server_channel, notice: "Channel was successfully updated." }
          format.json { render :show, status: :ok, location: @server_channel }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @server_channel.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /server/channels/1 or /server/channels/1.json
    def destroy
      @server_channel.destroy!

      respond_to do |format|
        format.html { redirect_to server_channels_path, status: :see_other, notice: "Channel was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private
      def set_server
        @server = Server.find(params[:server_id])
      end

      # Use callbacks to share common setup or constraints between actions.
      def set_server_channel
        @server_channel = Server::Channel.find(params.expect(:id))
      end

      # Only allow a list of trusted parameters through.
      def server_channel_params
        params.expect(server_channel: [ :name ])
      end
  end
end

app/controllers/servers/invite_links_controller.rb
module Servers
  class InviteLinksController < BaseController
    before_action :set_server, :authorize_owner!

    def show
      @invite_link = @server.invite_links.find(params[:id])
    end

    def create
      @invite_link = @server.invite_links.create
      redirect_to server_invite_link_path(@server, @invite_link)
    end
    
  private
    def set_server
      @server = current_user.owned_servers.find(params[:server_id])
    end
  end
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_action :set_server, only: %i[ show edit update destroy ]

  # GET /servers or /servers.json
  def index
    @servers = Server.all
  end

  # GET /servers/1 or /servers/1.json
  def show
  end

  # GET /servers/new
  def new
    @server = Server.new
  end

  # GET /servers/1/edit
  def edit
  end

  # POST /servers or /servers.json
  def create
    @server = current_user.owned_servers.new(server_params)

    if @server.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /servers/1 or /servers/1.json
  def update
    if @server.update(server_params)
      redirect_to @server, notice: "Server was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /servers/1 or /servers/1.json
  def destroy
    @server.destroy!

    respond_to do |format|
      format.html { redirect_to servers_path, status: :see_other, notice: "Server was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_server
      @server = Server.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def server_params
      params.expect(server: [ :name, :image ])
    end
end

app/helpers/server/channels_helper.rb
module Server::ChannelsHelper
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/servers/_form.html.erb
<%= form_with(model: server, class: "contents") do |form| %>
  <% if server.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(server.errors.count, "error") %> prohibited this server from being saved:</h2>

      <ul class="list-disc ml-6">
        <% server.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name, class: "text-gray-100" %>
    <%= form.text_field :name, class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": server.errors[:name].none?, "border-red-400 focus:outline-red-600": server.errors[:name].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :image, class: "text-gray-100" %>
    <%= form.file_field :image, class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": server.errors[:image].none?, "border-red-400 focus:outline-red-600": server.errors[:image].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/servers/_server.html.erb
<div id="<%= dom_id server %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= server.name %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Owner:</strong>
    <%= server.owner_id %>
  </p>
</div>

app/views/servers/_sidebar.html.erb
<div class="w-80 min-h-screen bg-gray-600 flex flex-col p-4 fixed left-36 z-[555]" data-sidebar-target="sidebar"
  id="server-sidebar" data-turbo-permanent> 
  <% if @server.owner == current_user %>
    <div class="flex justify-end w-full"> 
      <%= link_to "Create channel", new_server_channel_path(@server), class: "text-lg text-gray-100 px-3 py-2 rounded-lg bg-blue-500" %>
    </div>
  <% end %>
  <div class="flex flex-col gap-2 mt-4">
    <% @server.channels.each do |channel| %>
      <%= link_to server_channel_path(@server, channel), data: { turbo_frame: :dashboard, action: "sidebar#toggle", sidebar_skip_prevent_param: true } do %>
        <div class="flex gap-2 items-center">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-8 text-gray-100">
            <path stroke-linecap="round" stroke-linejoin="round" d="M7.5 8.25h9m-9 3H12m-9.75 1.51c0 1.6 1.123 2.994 2.707 3.227 1.129.166 2.27.293 3.423.379.35.026.67.21.865.501L12 21l2.755-4.133a1.14 1.14 0 0 1 .865-.501 48.172 48.172 0 0 0 3.423-.379c1.584-.233 2.707-1.626 2.707-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0 0 12 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018Z" />
          </svg>
          <span class="text-xl text-gray-100 hover:underline"> <%= channel.name %> </span>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/servers/edit.html.erb
<% content_for :title, "Editing server" %>

<%= turbo_frame_tag :dashboard do %>
  <div class="w-full flex justify-center pt-24">
    <div class="max-w-2xl w-full bg-gray-600 p-4 rounded-lg">
      <h1 class="font-bold text-4xl text-gray-100">Edit server</h1>

      <%= render "form", server: @server %>

      <%= link_to "Cancel", @server, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
    </div>
  </div>
<% end %>

app/views/servers/index.html.erb
<% content_for :title, "Servers" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Servers</h1>
    <%= link_to "New server", new_server_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="servers" class="min-w-full">
    <% if @servers.any? %>
      <% @servers.each do |server| %>
        <%= render server %>
        <p>
          <%= link_to "Show this server", server, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
        </p>
      <% end %>
    <% else %>
      <p class="text-center my-10">No servers found.</p>
    <% end %>
  </div>
</div>

app/views/servers/new.html.erb
<% content_for :title, "New server" %>

<%= turbo_frame_tag :dashboard do %>
  <div class="w-full flex justify-center pt-24">
    <div class="max-w-2xl w-full bg-gray-600 p-4 rounded-lg">
      <h1 class="font-bold text-4xl text-gray-100">New server</h1>

      <%= render "form", server: @server %>

      <%= link_to "Cancel", root_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
    </div>
  </div>
<% end %>

app/views/servers/show.html.erb
<% content_for :title, "Showing server" %>

<%= turbo_frame_tag :dashboard do %>
  <div class="flex">
    <%= render "sidebar" %>
    <div class="w-full h-screen pt-8">
      <div class="w-full flex flex-col items-center">
        <h1 class="text-2xl text-gray-100 text-center"> <%= @server.name %> </h1>
        <%= image_tag(@server.image, class: "w-24 h-24 rounded-full object-cover") if @server.image.attached? %>
      </div>
      <% if @server.owner == current_user %>
        <div class="w-full flex gap-4 justify-end px-4">
          <%= link_to "Edit server", edit_server_path(@server), class: "text-gray-100 px-3 py-2 rounded-lg bg-blue-500" %>
          <%= link_to "Create invite link", server_invite_links_path(@server), class: "text-gray-100 px-3 py-2 rounded-lg bg-indigo-500",
            data: { turbo_method: :post } %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>