config/routes.rb
Rails.application.routes.draw do
  resources :servers do
    scope module: :servers do
      resources :invite_links, only: [:show, :create]
      resources :channels do
        scope module: :channels do
          resources :messages, only: [:create]
        end
      end
    end
  end

  get "/invite/:uniq_id", to: "invitations#show"
  resources :invitations, only: [:create]
  
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboard#show"
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :set_invite_link
  def show
  end

  def create
    redirect_to root_path, alert: "Invalid invite link" unless @invite_link.present?
    # Handle creating membership to server
    current_user.server_memberships.find_or_create_by(server: @invite_link.server)
    redirect_to root_path
  end
private
  def set_invite_link
    @invite_link = Server::InviteLink.find_by_uniq_id(params[:uniq_id])
  end
end

app/views/invitations/show.html.erb
<div class="w-full h-screen flex flex-col items-center pt-24">
  <% if @invite_link %>
    <div class="max-w-2xl h-[40vh] w-full rounded-lg bg-gray-600 flex flex-col items-center p-4 pb-16"> 
      <h1 class="text-3xl text-gray-100"> You were invited to join a server </h1>
      <h2 class="text-5xl text-gray-100"> <%= @invite_link.server_name %> </h2>
      
      <p class="text-xl text-gray-200"> Owned by <%= @invite_link.server.owner.username %></p>
      
      <%= link_to "Join Server", invitations_path(uniq_id: @invite_link.uniq_id), class: "px-3 py-2 rounded-lg text-3xl bg-blue-500 text-blue-50 mt-auto hover:scale-105 hover:bg-blue-600",
        data: { turbo_method: :post } %>
    </div>
  <% else %>
    <h1 class="text-3xl text-gray-900"> Sorry we could not find a server for that link </h1>
  <% end %>
</div>